import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import type { ScanRecord } from "./storage";

export function generateReportPdf(scan: ScanRecord) {
  const doc = new jsPDF();
  const margin = 14;
  let y = 18;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text("Legal Metrology Compliance Report", margin, y);
  y += 6;

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text("Legal Metrology (Packaged Commodities) Rules, 2011", margin, y);
  y += 8;

  doc.setDrawColor(30, 64, 175);
  doc.setLineWidth(0.6);
  doc.line(margin, y, 210 - margin, y);
  y += 8;

  doc.setFont("helvetica", "bold");
  doc.text(`Product: ${scan.productName}`, margin, y);
  y += 6;
  doc.setFont("helvetica", "normal");
  doc.text(`Inspector: ${scan.inspector}    Location: ${scan.location}`, margin, y);
  y += 6;
  doc.text(`Scanned At: ${new Date(scan.scannedAt).toLocaleString()}`, margin, y);
  y += 6;
  doc.text(`Report ID: ${scan.id}`, margin, y);
  y += 8;

  doc.setFont("helvetica", "bold");
  doc.text("Key Declarations", margin, y);
  y += 4;
  autoTable(doc, {
    startY: y,
    head: [["Field", "Value"]],
    body: [
      ["Manufacturer", scan.manufacturer ?? "—"],
      ["Net Quantity", scan.netQuantity ?? "—"],
      ["MRP", scan.mrp ? `Rs. ${scan.mrp}` : "—"],
      ["Manufacturing Date", scan.mfgDate ?? "—"],
    ],
    theme: "striped",
    headStyles: { fillColor: [29, 78, 216] },
    margin: { left: margin, right: margin },
  });
  y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 6;

  if (scan.fontFindings && scan.fontFindings.length > 0) {
    if (y > 240) { doc.addPage(); y = 20; }
    doc.setFont("helvetica", "bold");
    doc.text("Font Size & Readability Analysis", margin, y);
    y += 4;
    autoTable(doc, {
      startY: y,
      head: [["Field", "Detected Text", "Height %", "Status", "Notes"]],
      body: scan.fontFindings.map((f) => [
        f.field,
        f.matchedText,
        `${f.heightPctOfImage.toFixed(2)}%`,
        f.rating.toUpperCase(),
        f.message,
      ]),
      theme: "grid",
      headStyles: { fillColor: [29, 78, 216] },
      styles: { fontSize: 9, cellPadding: 3 },
      margin: { left: margin, right: margin },
    });
    y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 6;
  }

  doc.setFont("helvetica", "bold");
  doc.text(`Compliance Score: ${scan.score}%   Status: ${scan.compliant ? "COMPLIANT" : "NON-COMPLIANT"}`, margin, y);
  y += 4;
  doc.setFont("helvetica", "normal");
  doc.text(
    `Critical: ${scan.criticalCount}  Major: ${scan.majorCount}  Minor: ${scan.minorCount}`,
    margin,
    y
  );
  y += 8;

  doc.setFont("helvetica", "bold");
  doc.text("Rule-wise Findings", margin, y);
  y += 4;
  autoTable(doc, {
    startY: y,
    head: [["Mandatory Declaration", "Rule Ref", "Status", "Notes"]],
    body: scan.violations.map((v) => [
      v.ruleName,
      v.ruleRef,
      v.matched ? "OK" : v.severity.toUpperCase(),
      v.matched ? `Found: ${v.matchedValue ?? ""}` : v.message,
    ]),
    theme: "grid",
    headStyles: { fillColor: [29, 78, 216] },
    styles: { fontSize: 9, cellPadding: 3 },
    columnStyles: { 2: { cellWidth: 24 }, 3: { cellWidth: 70 } },
    margin: { left: margin, right: margin },
  });

  const pageHeight = doc.internal.pageSize.getHeight();
  doc.setFontSize(8);
  doc.setTextColor(100);
  doc.text(
    "Generated by Legal Metrology Compliance Checker. This is a system-generated report for inspection purposes.",
    margin,
    pageHeight - 8
  );

  doc.save(`LM-Report-${scan.id}.pdf`);
}
